# Generated by Django 5.2.1 on 2025-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completion_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='worked_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
